frontend/src/components/common/MyCarDescription/index.tsx, frontend/src/components/common/MyCarImageBox/index.tsx, frontend/src/components/common/MyCarImageBox/style.tsx, frontend/src/components/common/TrimCard/index.tsx, frontend/src/components/common/TrimCard/style.tsx, frontend/src/components/templates/trim/TrimTemplate.tsx
=> refact: 변수명 변경 및 인터페이스 수정

frontend/src/components/common/Navigation/index.tsx, frontend/src/components/common/Navigation/style.tsx, frontend/src/components/common/header/index.tsx, frontend/src/components/common/header/style.tsx, frontend/src/components/layout/MyCarLayout/style.tsx
=> [FE] 레이아웃 수정

README.md
- API 명세서 LINK 추가
Closes softeerbootcamp-2nd/H9-88Hey#5
=> [BE] API 명세서 작성

.github/workflows/backend_CICD.yml, backend/build.gradle
github action workflow 스크립트 작성
EC2 인스턴스 배포 환경 세팅(JDK11, nginx)
PR시에 코드 테스트, 깃 컨벤션 체크 스크립트 작성에 대한 의견 남겨주세요.
Close #9
=> [BE] 자동화 배포 초기 세팅

.github/workflows/backend_CICD.yml
자동 배포 시 mysql 접속 세팅을 위해 workflow 환경변수 설정.
테스트 시 사설 IP 이슈로 인해 CICD에서 CD로 전환
=> [BE] MySQL 접속 세팅

frontend/src/mocks/api/body-type/data.ts, frontend/src/mocks/api/body-type/index.ts, frontend/src/mocks/api/engine/data.ts, frontend/src/mocks/api/engine/index.ts, frontend/src/mocks/api/trim-color/data.ts, frontend/src/mocks/api/trim-color/index.ts, frontend/src/mocks/api/trim-default-option/data.ts, frontend/src/mocks/api/trim-h-genuine-accessories/data.ts, frontend/src/mocks/api/trim-n-performance/data.ts, frontend/src/mocks/api/trim-select-option/data.ts, frontend/src/mocks/api/trim/data.ts, frontend/src/mocks/api/trim/index.ts, frontend/src/mocks/api/wheel-drive/data.ts, frontend/src/mocks/api/wheel-drive/index.ts
- api 수정
- Url 경로는 업데이트 안된거 같아서 기존으로 써주세여~
closes #54
=> [FE] MSW Api 수정

backend/src/main/java/softeer/h9/hey/dto/response/GlobalResponse.java
- 모든 응답에 공통적으로 적용할 Response Dto 구현
- message나 data가 null이면 응답시 직렬화 하지 않도록 함.
Closes #57
=> [BE] Global Response DTO 구현

backend/src/main/java/softeer/h9/hey/controller/car/TrimController.java, backend/src/main/java/softeer/h9/hey/domain/car/Trim.java, backend/src/main/java/softeer/h9/hey/domain/car/TrimFeature.java, backend/src/main/java/softeer/h9/hey/dto/car/response/TrimsResponse.java, backend/src/main/java/softeer/h9/hey/repository/car/TrimRepository.java, backend/src/main/java/softeer/h9/hey/service/car/TrimService.java, backend/src/test/java/softeer/h9/hey/controller/car/TrimControllerTest.java, backend/src/test/java/softeer/h9/hey/repository/car/TrimRepositoryTest.java, backend/src/test/java/softeer/h9/hey/service/car/TrimServiceTest.java
- 트림, 트림 특징 도메인 클래스 구현
- DB에서 model id를 통해 트림을 조회하는 기능 구현
- 조회한 트림을 응답 형식에 맞춰 반환하는 기능 구현
- 위의 기능들을 테스트하는 코드 구현
- 코드 리뷰 잘 부탁드립니다! 👍 👍 👍 
Close #63
=> [BE] 트림 조회 기능

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomBars.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/ColorSelectItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimViewModel.kt
* merge로 인해 발생한 컴파일 오류 유발 코드 수정
* 누락 dummy data 추가
=> [AND] 누락 코드 추가 및 오류 수정

backend/src/main/java/softeer/h9/hey/controller/car/CarInfoController.java, backend/src/main/java/softeer/h9/hey/domain/car/CarInfo.java, backend/src/main/java/softeer/h9/hey/dto/car/request/CarCodeRequest.java, backend/src/main/java/softeer/h9/hey/dto/car/response/CarCodeResponse.java, backend/src/main/java/softeer/h9/hey/repository/car/CarInfoRepository.java, backend/src/main/java/softeer/h9/hey/service/car/CarInfoService.java, backend/src/test/java/softeer/h9/hey/controller/car/CarInfoControllerTest.java, backend/src/test/java/softeer/h9/hey/repository/car/CarInfoRepositoryTest.java, backend/src/test/java/softeer/h9/hey/service/car/CarInfoServiceTest.java
- DB로부터 트림, 엔진, 구동방식, 바디타입 ID를 통해 CarInfo 조회 기능
- 특정 구성(트림, 엔진, 바디타입, 구동방식)을 갖는 CarInfo로부터 CarCode를 가져오는 기능
- 차량 통합 코드 요청 처리 기능
- 비즈니스 로직상 발생하는 예외에 대해서 커스텀 예외 사용을  고려해봐야할 듯 합니다.
Close #64
=> [BE] 차량 통합 코드 조회

android/MyCarchiving/app/build.gradle.kts, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/RotateCarImage.kt, android/MyCarchiving/gradle/libs.versions.toml
* `GlideImage` -> `AsnycImage` 변경 후, `preload` 정상 작동 확인
=> [AND] 이미지 preload 오류 수정

backend/src/main/java/softeer/h9/hey/controller/car/WheelDriveController.java, backend/src/main/java/softeer/h9/hey/domain/car/WheelDrive.java, backend/src/main/java/softeer/h9/hey/dto/car/response/WheelDriveResponse.java, backend/src/main/java/softeer/h9/hey/repository/car/WheelDriveRepository.java, backend/src/main/java/softeer/h9/hey/service/car/WheelDriveService.java, backend/src/test/java/softeer/h9/hey/controller/car/WheelDriveControllerTest.java, backend/src/test/java/softeer/h9/hey/repository/car/WheelDriveRepositoryTest.java, backend/src/test/java/softeer/h9/hey/service/car/WheelDriveServiceTest.java
- 특정 모델에서 사용되는 구동 방식 조회 기능 구현
- 특정 모델에서 사용되는 구동 방식 조회 기능 테스트 구현
Close #62
=> [BE] 구동 방식 조회 기능 구현

frontend/src/components/review/OptionList/index.tsx, frontend/src/components/review/OptionList/style.tsx, frontend/src/components/review/ReviewButton/index.tsx, frontend/src/components/review/ReviewButton/style.tsx, frontend/src/components/review/ReviewDescription/index.tsx, frontend/src/components/review/ReviewDescription/style.tsx, frontend/src/components/review/ReviewImageCard/index.tsx, frontend/src/components/review/ReviewImageCard/style.tsx, frontend/src/components/review/ReviewOption/index.tsx, frontend/src/components/review/ReviewOption/style.tsx, frontend/src/components/review/ReviewTag/index.tsx, frontend/src/components/review/ReviewTag/style.tsx, frontend/src/components/review/ReviewTextArea/index.tsx, frontend/src/components/review/ReviewTextArea/style.tsx, frontend/src/components/review/SlidePrevButton/index.tsx, frontend/src/components/review/SlidePrevButton/style.tsx, frontend/src/constants/index.ts, frontend/src/mocks/api/review/data.ts, frontend/src/mocks/api/review/index.ts, frontend/src/pages/Review/index.tsx, frontend/src/pages/Review/style.tsx, frontend/src/routes/router.tsx, frontend/src/styles/theme.ts
- 리뷰페이지 생성
- UI 구현
- 캐러셀 적용
- 디자인 좀더 좋게할수있으면 얘기해보져
데모
https://github.com/softeerbootcamp-2nd/H9-88Hey/assets/101790391/2a62df91-7727-402b-ba94-94eddd2d40e7
Close #90
=> [FE] 리뷰 페이지 UI 구현

android/MyCarchiving/app/build.gradle.kts, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/TrimOptionUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/makingcar/ColorOptionUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/HyundaiApp.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomBars.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomSheetItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/CompleteItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/NavigateBars.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/OptionSelectItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/MakingCarViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/complete/CompleteScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimViewModel.kt, android/MyCarchiving/app/src/main/res/values/strings.xml, android/MyCarchiving/data/src/main/java/com/softeer/data/CarColorType.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/TrimType.kt, android/MyCarchiving/gradle/libs.versions.toml
* `MakingCarViewModel`에 공용 상태 변수 선언
* 각종 `UiModel` 속성 수정
* 견적요약보기 - `MakingCarViewModel` 연동
=> [AND] 내차만들기 - 견적요약보기 임시 연동

android/MyCarchiving/app/build.gradle.kts, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/TrimOptionUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/makingcar/ColorOptionUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/HyundaiApp.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomBars.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomSheetItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/CompleteItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/NavigateBars.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/OptionSelectItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/MakingCarViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/complete/CompleteScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimViewModel.kt, android/MyCarchiving/app/src/main/res/values/strings.xml, android/MyCarchiving/data/src/main/java/com/softeer/data/CarColorType.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/TrimType.kt, android/MyCarchiving/gradle/libs.versions.toml
=> [AND]  누락 코드 수정

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/MakingCarViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimScreen.kt
=> [AND] 견적요약보기 로직 수정

backend/src/main/java/softeer/h9/hey/controller/car/DefaultOptionController.java, backend/src/main/java/softeer/h9/hey/domain/car/DefaultOption.java, backend/src/main/java/softeer/h9/hey/domain/car/DefaultOptionCategory.java, backend/src/main/java/softeer/h9/hey/dto/car/DefaultOptionDto.java, backend/src/main/java/softeer/h9/hey/dto/car/DefaultSubOptionDto.java, backend/src/main/java/softeer/h9/hey/dto/car/request/DefaultOptionRequest.java, backend/src/main/java/softeer/h9/hey/dto/car/response/DefaultOptionsResponse.java, backend/src/main/java/softeer/h9/hey/repository/Car/DefaultOptionRepository.java, backend/src/main/java/softeer/h9/hey/service/car/DefaultOptionService.java, backend/src/test/java/softeer/h9/hey/controller/car/DefaultOptionControllerTest.java, backend/src/test/java/softeer/h9/hey/repository/Car/DefaultOptionRepositoryTest.java, backend/src/test/java/softeer/h9/hey/service/car/DefaultOptionServiceTest.java
- 기본 옵션 조회 기능 구현
- 기본 옵션 조회 테스트 작성
Close #93
=> [BE] 내 차 만들기 기본 옵션 조회

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/di/DataModule.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/di/MakingCarApiModule.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/makingcar/SelectOptionUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/CompleteItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/OptionSelectItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/MakingCarNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/complete/CompleteScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimScreen.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/SelectOptionDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/SelectTrimDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/TrimOptionDtos.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/SelectOptionNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/SelectOptionRepository.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/SelectTrimRepository.kt
* `선택옵션` 네트워크 연결
* `H-Genuine` 네트워크 연결
* `N Performance` 네트워크 연결
* `옵션선택` Screen UI 보완
=> [AND] 내차만들기 옵션선택 네트워크 연결

backend/src/main/java/softeer/h9/hey/controller/car/ColorDataController.java, backend/src/main/java/softeer/h9/hey/dto/car/response/ColorDataResponse.java, backend/src/main/java/softeer/h9/hey/repository/car/InteriorColorRepository.java, backend/src/test/java/softeer/h9/hey/controller/car/ColorDataControllerTest.java, backend/src/test/java/softeer/h9/hey/repository/car/InteriorColorRepositoryTest.java, backend/src/test/java/softeer/h9/hey/service/car/ColorDataServiceTest.java
=> [BE] 내장 색상 자동차 이미지 URL 누락 픽스

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/di/NetworkModule.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomSheetItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/Dialogs.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionViewModel.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/SelectOptionDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/TrimOptionDtos.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/SelectColorNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/SelectOptionNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/SelectTrimNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/SelectOptionRepository.kt
* 기본 요약 품목 `BottomSheet`에 네트워크 데이터 연결
* 추후 UI 보완 및 점검 필요할 듯
=> [AND] 기본 요약 품목 네트워크 연결

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/MakingCarNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/complete/CompleteNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimNavigation.kt
* `내차만들기` 영역에서 `BackHandler` 등록해서 Back button 클릭 시 `appState.onBackProgress()` 호출하도록 변경
=> [AND] 내차만들기 Back Button 클릭 시 화면 전환 보완

backend/src/main/java/softeer/h9/hey/dto/car/response/HGenuineAccessoryResponse.java, backend/src/test/java/softeer/h9/hey/controller/car/SelectOptionControllerTest.java
- h-genuine isAvailable 응답 위치 수정
- 승원님 수정했습니다! 🫡 @sukam09 
Close #138
=> [BE] h-genuine isAvailable 응답 위치 수정

frontend/src/App.tsx, frontend/src/CacheProvider.tsx, frontend/src/components/Archiving/ReviewCard/index.tsx, frontend/src/components/Option/OptionCardList/index.tsx, frontend/src/components/common/Footer/EstimateModal/index.tsx, frontend/src/components/common/Footer/EstimateModal/style.tsx, frontend/src/components/common/Footer/index.tsx, frontend/src/components/common/Header/index.tsx, frontend/src/components/common/Header/style.tsx, frontend/src/components/common/ModalProvider/index.tsx, frontend/src/components/common/PopupModal/index.tsx, frontend/src/components/layout/MyCarLayout/index.tsx, frontend/src/constants/index.ts, frontend/src/hooks/useCacheQuery.ts, frontend/src/main.tsx, frontend/src/pages/Archiving/Detail/index.tsx, frontend/src/pages/Color/index.tsx, frontend/src/pages/MyChiving/index.tsx, frontend/src/pages/Trim/BodyType/index.tsx, frontend/src/pages/Trim/Engine/index.tsx, frontend/src/pages/Trim/WheelDrive/index.tsx, frontend/src/pages/Trim/index.tsx, frontend/src/routes/router.tsx, frontend/src/types/cache.ts, frontend/src/types/option.ts, frontend/src/types/trim.ts, frontend/src/utils/index.ts
- api 캐시 구현
- queryString 적용
- api 캐시는 프로토타입이라 넘겨주세여!
Close #121
=> [FE] api 캐시 및 queryString 적용

backend/build.gradle
- 스웨거 의존성을 추가한다.
- api.88hey.site:8080/swagger-ui/index.html
Close #141
=> #141 config: swagger 의존성 추가

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionScreen.kt
=> [AND] 내 차 만들기 UI 보안 병합

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/ColorSelectItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/RotateCarImage.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/complete/CompleteNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectmodel/SelectModelNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectmodel/SelectModelScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/util/TransitionSpecGenerator.kt
* Navigation 화면 전환 Transition 적용
* 이미지 캐싱
* 모델선택 진입 전 이미지 캐싱
* 색상선택 진입 전 360도 이미지 및 인테리어 이미지 캐싱
* 선택옵션 진입 전 이미지 캐싱
=> [AND] 화면 전환 Transition 적용 및 진입 전 이미지 캐싱

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/RotateCarImage.kt
=> [AND] 360도 이미지 드래그로 변경

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/MakingCarNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/util/MakeCarProcess.kt
* 화면 진행 상태값 상수 변수로 관리
* 리컴포지션 발생하지 않도록 분기 처리
=> [AND] 화면 전환 시 발생하는 리컴포지션 임시 방지

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/HyundaiAppState.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/ArchivingNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/MakingCarNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/MyArchivingNavigation.kt
* destination 재진입 시 앱 강제 종료 되는 버그 제거
=> [AND] 재진입 시 앱 강제종료 되는 버그 제거

android/MyCarchiving/app/build.gradle.kts, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/di/ArchivingApiModule.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/di/DataModule.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/mapper/ArchivingUiModelMapper.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/common/CarFeedUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingmain/ArchiveScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingmain/ArchiveViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/ArchiveListItem.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/MyArchiveListItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/main/MyArchiveMainScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/main/MyArchiveMainViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/save/MyArchiveSaveScreen.kt, android/MyCarchiving/data/build.gradle.kts, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/ArchivingDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/ArchivingRemotePagingSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/mapper/ArchivingMapper.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/ArchivingDtos.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/ArchivingNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/ArchivingRepositoryImpl.kt, android/MyCarchiving/domain/build.gradle.kts, android/MyCarchiving/domain/src/main/java/com/softeer/domain/model/CarColor.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/model/CarExtraOption.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/model/CarFeed.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/model/SelectOption.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/model/TrimOption.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/repository/ArchivingRepository.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/archiving/GetAbleOptionsUseCase.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/archiving/GetCarFeedsUseCase.kt, android/MyCarchiving/gradle/libs.versions.toml
* 아카이빙 홈 `Paging` 연결
* 선택 옵션 데이터 네트워크에서 로드
* 선택 옵션으로 필터링하는 로직 및 UI 보완 필요함
=> [AND] 아카이빙 네트워크 데이터 로드

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/mapper/ColorOptionUiModelMapper.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/makingcar/ColorOptionUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/CompleteItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/OptionSelectItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/complete/CompleteScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectoption/SelectOptionViewModel.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/SelectColorDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/SelectOptionDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/TagDto.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/SelectColorNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/SelectOptionNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/SelectColorRepositoryImpl.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/SelectOptionRepositoryImpl.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/repository/SelectColorRepository.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/repository/SelectOptionRepository.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/makingcar/GetTagsOfExteriorUseCase.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/makingcar/GetTagsOfInteriorUseCase.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/makingcar/GetTagsOfSelectOptionUseCase.kt
* `DataSource` 및 `Repository`에 색상선택/선택옵션 태그 데이터 내려받기 구현
* `ViewModel`에서 태그 데이터 요청 및 저장
=> [AND] 색상선택/선택옵션 태그 데이터 네트워크 연결

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/mapper/ArchivingUiModelMapper.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/archiving/SearchOptionUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/common/CarFeedUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/ArchivingNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingmain/ArchiveScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingmain/ArchiveViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/ArchiveListItem.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/MyArchiveListItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/main/MyArchiveMainScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/main/MyArchiveMainViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/save/MyArchiveSaveScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/util/SearchCarOptions.kt
* 아카이빙 `리스트 UI 보완`
* 선택한 옵션 `맨 앞`, `색 변경`으로 표시
* 아카이빙 `검색 로직` 변경
* 아카이빙 `상세 화면` 네트워크 연결 필요
=> [AND] 아카이빙 UI 보완 및 네트워크 로직 수정

android/MyCarchiving/app/.gitignore, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/MainActivity.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/di/DataModule.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/di/SignApiModule.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/LoginItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/login/LoginScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/login/LoginViewModel.kt, android/MyCarchiving/app/src/main/res/values/strings.xml, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/SignDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/mapper/SignMapper.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/SignInRequestDto.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/TokenDto.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/SignNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/SignRepositoryImpl.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/model/Token.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/repository/SignRepository.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/sign/SignInUseCase.kt
* 로그인 화면 `컴포넌트` 선언
* 로그인 화면 `구현과 상태관리`
* 로그인 기능 네트워크 연결
* `토큰` 관리하는 방식
=> [AND] 로그인 화면과 네트워크 연결

backend/src/main/java/softeer/h9/hey/domain/car/ExteriorColor.java, backend/src/main/java/softeer/h9/hey/domain/car/InteriorColor.java, backend/src/main/java/softeer/h9/hey/dto/car/response/HGenuineAccessoryResponse.java, backend/src/main/java/softeer/h9/hey/dto/car/response/SelectOptionResponse.java
내 차 만들기 태그 응답 부분을 삭제한다.
Close #193
=> [BE] 내 차 만들기 태그 응답 삭제

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/DetailItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/Dialogs.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/MyArchiveListItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/detail/MyArchiveDetailScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/detail/MyArchiveDetailViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/main/MyArchiveMainScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/main/MyArchiveMainViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/save/MyArchiveSaveScreen.kt, android/MyCarchiving/app/src/main/res/values/strings.xml
* 마이카이빙 내가 만든 차량 제거 시도시 Dialog 송출
* 더미 데이터 임시 설정
=> [AND] 마이카이빙 UI 보완 및 더미 데이터 임시 설정

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/HyundaiApp.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/HyundaiAppState.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomBars.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/RotateCarImage.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/MyArchivingNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/detail/MyArchiveDetailScreen.kt
- 마이카이빙 BottomBar 연결
- 마이카이빙 TopBar 뒤로가기 오류 수정
- 미사용 코드 제거
=> [AND] 마이카이빙 BottomBar 구현 및 리팩토링

backend/src/main/java/softeer/h9/hey/auth/config/AuthWebConfig.java
- 스웨거 API 페이지 필터 적용.
Close #209
=> [BE] Hotfix 스웨거 페이지 인증 필터 제거

backend/src/main/java/softeer/h9/hey/controller/myChiving/MyChivingController.java, backend/src/main/java/softeer/h9/hey/dto/myChiving/response/MyChivingResponse.java, backend/src/main/java/softeer/h9/hey/dto/myChiving/response/MyChivingsResponse.java, backend/src/main/java/softeer/h9/hey/service/myChiving/MyChivingService.java, backend/src/test/java/softeer/h9/hey/service/myChiving/MyChivingServiceTest.java
- nextOffset 제공
- modelDto -> model
nextOffset을 null 처리해주는 로직이 적합한지 봐주시면 감사하겠습니다!
Close #211
=> [BE] 마이카이빙 조회 response 수정

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/mapper/ArchivingUiModelMapper.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/common/CarDetailsUiModels.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/makingcar/ColorOptionSimpleUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/HyundaiAppState.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/ArchiveKeys.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/ArchivingNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingdetail/ArchiveDetailViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingdetail/ArchivingDetailNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingdetail/ArchivingDetailScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingmain/ArchiveMainNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingmain/ArchiveScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/ArchiveListItem.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/DetailItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/detail/MyArchiveDetailScreen.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/ArchivingDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/mapper/ArchivingMapper.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/ArchivingDtos.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/ArchivingNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/ArchivingRepositoryImpl.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/model/CarDetails.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/model/CarExtraOption.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/repository/ArchivingRepository.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/archiving/GetCarDetailsUseCase.kt
* 아카이빙 상세화면 관련 Entity, DTO, UiModel 선언
* 아카이빙 상세화면 네트워크 데이터 연결
* 아카이빙 상세화면 UI 보완
=> [AND] 아카이빙 상세화면 네트워크 연결

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/HyundaiAppState.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomBars.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomSheetItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/Dialogs.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/MyArchiveListItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/NavigateBars.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/OptionSelectItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/ProgressBar.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/TrimSelectItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/MakingCarNavigation.kt
* 내 차 만들기 `ui 보완`과 `로직 수정`
* 마이카이빙 `ui 보완`과 `코드 정리`
* `애니메이션` 수정
=> [AND] QA 반영하기

backend/src/main/java/softeer/h9/hey/controller/myChiving/MyChivingController.java, backend/src/main/java/softeer/h9/hey/exception/myChiving/DeletionFailException.java, backend/src/main/java/softeer/h9/hey/exception/myChiving/InValidAccessException.java, backend/src/main/java/softeer/h9/hey/repository/myChiving/MyChivingRepository.java, backend/src/main/java/softeer/h9/hey/service/myChiving/MyChivingService.java, backend/src/test/java/softeer/h9/hey/controller/myChiving/MyChivingControllerTest.java, backend/src/test/java/softeer/h9/hey/repository/car/SelectOptionRepositoryTest.java, backend/src/test/java/softeer/h9/hey/repository/myChiving/MyChivingRepositoryTest.java
- 유저정보와 마이카이빙 아이디를 통해 마이카이빙을 삭제한다.
Close #221
=> [BE] 마이카이빙 삭제 구현

backend/src/main/java/softeer/h9/hey/controller/archiving/ArchivingController.java, backend/src/main/java/softeer/h9/hey/dto/archiving/ArchivingDto.java, backend/src/main/java/softeer/h9/hey/dto/archiving/response/ArchivingDetailResponse.java, backend/src/main/java/softeer/h9/hey/dto/myChiving/response/MyChivingIdResponse.java, backend/src/main/java/softeer/h9/hey/dto/myChiving/response/MyChivingResponse.java, backend/src/main/java/softeer/h9/hey/service/archiving/ArchivingService.java, backend/src/test/java/softeer/h9/hey/controller/archiving/ArchivingControllerTest.java, backend/src/test/java/softeer/h9/hey/service/archiving/ArchivingServiceTest.java, backend/src/test/java/softeer/h9/hey/service/myChiving/MyChivingServiceTest.java
- 아카이빙 상세 조회 타입 및 uri 변경
Close #223
=> [BE] 아카이빙 상세 조회 타입 및 URI 수정

backend/src/main/java/softeer/h9/hey/dto/myChiving/MyChivingSelectOptionDto.java, backend/src/main/java/softeer/h9/hey/dto/myChiving/MyChivingSelectOptionFetchDto.java, backend/src/main/java/softeer/h9/hey/repository/myChiving/MyChivingRepository.java, backend/src/main/java/softeer/h9/hey/service/myChiving/MyChivingService.java, backend/src/test/java/softeer/h9/hey/repository/myChiving/MyChivingRepositoryTest.java, backend/src/test/java/softeer/h9/hey/service/myChiving/MyChivingServiceTest.java
- 마이카이빙 조회 시 response에 선택옵션의 카테고리 추가한다.
Close #239
=> [BE] 마이카이빙 선택옵션 카테고리 추가

backend/src/main/java/softeer/h9/hey/dto/archiving/response/ArchivingDetailResponse.java, backend/src/main/java/softeer/h9/hey/service/archiving/ArchivingService.java
- 북마크한 아카이빙 목록 조회시 응답에 태그를 포함하도록 구현
Close #247
=> [BE] 마이카이빙에서 북마크한 아카이빙 피드 응답에 태그 추가

frontend/src/components/Archiving/DetailDescription/index.tsx, frontend/src/components/Archiving/SearchBar/index.tsx, frontend/src/components/MyChiving/MySavedCar/index.tsx, frontend/src/components/Review/ReviewDescription/index.tsx, frontend/src/components/common/Footer/index.tsx, frontend/src/components/common/SaveButton/index.tsx, frontend/src/components/layout/MyCarLayout/index.tsx, frontend/src/hooks/useAuthMutation.ts, frontend/src/hooks/useFetchSuspense.ts, frontend/src/pages/Archiving/Detail/index.tsx, frontend/src/pages/Color/index.tsx, frontend/src/pages/Trim/index.tsx, frontend/src/types/archiving.ts, frontend/src/types/myChiving.ts
=> [FE] 로그인 기능 적용 

backend/src/main/java/softeer/h9/hey/domain/archiving/ArchivingResult.java, backend/src/main/java/softeer/h9/hey/dto/archiving/SelectOptionDto.java, backend/src/main/java/softeer/h9/hey/repository/archiving/ArchivingRepository.java, backend/src/main/java/softeer/h9/hey/service/archiving/ArchivingService.java
- 아카이빙 조회 기능에 선택옵션의 카테고리를 추가한다.
Close #249
=> [BE] 아카이빙 카테고리 기능 추가

android/MyCarchiving/app/build.gradle.kts, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/ColorSelectItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/CompleteItems.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/RotateCarImage.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimScreen.kt, android/MyCarchiving/gradle/libs.versions.toml
* `GlideImage` 사용 코드 제거 및 `Coil`로 통일
=> [AND] 이미지 라이브러리 Coil로 통일

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/model/myarchive/ArchiveFeedUiModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/HyundaiAppState.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingdetail/ArchiveDetailViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingdetail/ArchivingDetailScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/BottomBars.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/Buttons.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/MyArchiveKeys.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/MyArchivingNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/detail/MyArchiveDetailNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/detail/MyArchiveDetailScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/detail/MyArchiveDetailViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/made/MyArchiveMadeScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/main/MyArchiveMainNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/main/MyArchiveMainScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/main/MyArchiveMainViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/myarchive/save/MyArchiveSaveScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/util/FlowExtensions.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/MyArchiveDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/MyArchiveDtos.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/MyArchiveMadeDtos.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/model/MyArchiveSavedDtos.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/MyArchiveNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/MyArchiveRepositoryImpl.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/model/MyArchiveFeed.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/repository/MyArchiveRepository.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/myarchive/AddBookmarkUseCase.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/myarchive/CheckBookmarkedUseCase.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/myarchive/DeleteBookmarkUseCase.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/myarchive/DeleteMadeCarFeedUseCase.kt
* 마이카이빙/아카이빙 북마크 조회/추가/제거 기능 구현
* 마이카이빙 -> 내차만들기 기능 구현
* 마이카이빙 UI 및 로직 보완
* 저장한 차량 목록 상세 페이지 구현
* 저장한 차량 목록 북마크 제거시 페이징 데이터 강제 갱신
=> [AND] 북마크 기능 구현 및 화면 연결

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/MakingCarViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selectcolor/SelectColorScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/makingcar/selecttrim/SelectTrimScreen.kt
* 모델 재선택시 트림선택 데이터 불일치 오류 수정
* 트림 재선택시 색상선택 데이터 불일치 오류 수정
=> [AND] 모델/트림선택 초기화 시 데이터 미갱신 오류 수정

android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/MainActivity.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/di/NetworkModule.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/HyundaiAppState.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/ArchivingNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingdetail/ArchiveDetailViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingmain/ArchiveMainNavigation.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingmain/ArchiveScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/archiving/archivingmain/ArchiveViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/component/Buttons.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/login/LoginScreen.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/login/LoginViewModel.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/ui/theme/Theme.kt, android/MyCarchiving/app/src/main/java/com/softeer/mycarchiving/util/NetworkInterceptor.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/datasource/SignDataSource.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/network/SignNetworkApi.kt, android/MyCarchiving/data/src/main/java/com/softeer/data/repository/SignRepositoryImpl.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/repository/SignRepository.kt, android/MyCarchiving/domain/src/main/java/com/softeer/domain/usecase/sign/ReissueUseCase.kt
*  로그인 `상태 관리` 리팩터링
* 아카이빙 `상태 관리` 리팩터링
* 로그인 헤더 토큰 분기
=> [AND] 로그인과 상태 관리 리팩터링

frontend/src/components/Option/DefaultOptionCardList/index.tsx, frontend/src/components/common/ArchivingHeader/index.tsx, frontend/src/components/common/EmptyContent/index.tsx, frontend/src/components/common/EmptyContent/style.tsx, frontend/src/components/common/ErrorBoundary/index.tsx, frontend/src/components/common/Header/index.tsx, frontend/src/components/layout/AuthLayout/index.tsx, frontend/src/hooks/useAuthFetch.ts, frontend/src/hooks/useAuthInfiniteFetch.ts, frontend/src/hooks/useAuthMutation.ts, frontend/src/hooks/useErrorHandler.ts, frontend/src/hooks/useInfiniteFetch.ts, frontend/src/hooks/usePostRequest.ts, frontend/src/hooks/useReissueToken.ts, frontend/src/hooks/useValidateToken.ts, frontend/src/pages/NotFound/index.tsx, frontend/src/pages/NotFound/style.tsx, frontend/src/pages/Option/index.tsx, frontend/src/pages/Result/index.tsx, frontend/src/pages/Signin/index.tsx, frontend/src/pages/Signup/index.tsx, frontend/src/routes/router.tsx, frontend/src/utils/CommonError.ts
- 세션 만료 에러 바운더리에 구현
- 로그아웃 상태일 때 URL 직접 접근 차단
Close #275
=> [FE] 로그아웃 상태/세션 만료 에러 바운더리에 구현

frontend/src/components/Archiving/OptionList/index.tsx, frontend/src/components/MyChiving/MySavedCar/index.tsx, frontend/src/components/MyChiving/MySavedCar/style.tsx, frontend/src/components/Review/ReviewOption/index.tsx, frontend/src/components/Review/ReviewOption/style.tsx, frontend/src/hooks/useAuthInfiniteFetch.ts, frontend/src/pages/Review/index.tsx
=> [FE] 최종 리팩토링
